name: Go Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build for Windows
        run: |
          echo "Creating build directory for Windows..."
          mkdir -p build/windows
          GOOS=windows GOARCH=amd64 go build -o build/windows/dnstt-client.exe ./dnstt-client
          GOOS=windows GOARCH=amd64 go build -o build/windows/dnstt-server.exe ./dnstt-server
          ls -la build/windows

      - name: Build for Linux
        run: |
          echo "Creating build directory for Linux..."
          mkdir -p build/linux
          GOOS=linux GOARCH=amd64 go build -o build/linux/dnstt-client ./dnstt-client
          GOOS=linux GOARCH=amd64 go build -o build/linux/dnstt-server ./dnstt-server
          ls -la build/linux

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dnstt-binaries
          path: build/**
