name: Go Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:  # Добавьте этот блок для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: |
          echo "Creating build directory..."
          mkdir -p build
          echo "Building dnstt-client..."
          go build -o build/dnstt-client ./dnstt-client
          echo "Building dnstt-server..."
          go build -o build/dnstt-server ./dnstt-server
          echo "Contents of the build directory:"
          ls -la build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dnstt-binaries
          path: build/*          
