name: Go Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: |
          echo "=== Creating build directory ==="
          mkdir -p build
          ls -la

          echo "=== Building dnstt-client ==="
          if go build -o ./build/dnstt-client ./dnstt-client; then
            echo "dnstt-client build successful"
          else
            echo "dnstt-client build failed!" && exit 1
          fi

          echo "=== Building dnstt-server ==="
          if go build -o ./build/dnstt-server ./dnstt-server; then
            echo "dnstt-server build successful"
          else
            echo "dnstt-server build failed!" && exit 1
          fi

          echo "=== Checking build directory contents ==="
          ls -la ./build

      - name: Debug directories
        run: |
          echo "=== Current working directory ==="
          pwd
          echo "=== Contents of the repository root ==="
          ls -la

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dnstt-binaries
          path: build/*
